- name: "Deploy config"
  template:
    src=templates/rhel_ifcfg.j2
    dest=/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}

- name: "Restart network"
  service:
    name: network
    state: restarted
